version: '2.1'

parameters:
  parallelism:
    type: integer
    default: 1

orbs:
  node: circleci/node@7
  ruby: circleci/ruby@2
  test-optimization-circleci-orb: datadog/test-optimization-circleci-orb@1

jobs:
  test:
    parallelism: << pipeline.parameters.parallelism >>
    docker:
      - image: cimg/ruby:3.3.0-node
      - image: cimg/postgres:13.13
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
      - image: cimg/redis:7.0
    environment:
      RAILS_ENV: test
      NODE_ENV: test
      DATABASE_URL_TEST: postgres://postgres:postgres@localhost:5432/Forem_test
      DATABASE_NAME_TEST: Forem_test
      REDIS_URL: redis://localhost:6379
      BUNDLE_PATH: vendor/bundle
      BUNDLE_JOBS: 4
      DD_ENV: ci
      DD_SERVICE: forem-circleci
    steps:
      - checkout
      - restore_cache:
          keys:
            - ddtest-plan-{{ .Revision }}
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Copy .env
          command: cp .env_sample .env
      - run:
          name: Prepare database
          command: bundle exec rails db:test:prepare
      - test-optimization-circleci-orb/autoinstrument:
          languages: ruby
          site: datadoghq.eu
      - run:
          name: Precompile assets
          command: |
            bundle exec rails assets:precompile
      - run:
          name: Run tests with ddtest
          command: |
            NODE_INDEX=${CIRCLE_NODE_INDEX:-0}
            export DD_TEST_SESSION_NAME="forem-ci-${NODE_INDEX}"
            export DD_TEST_OPTIMIZATION_RUNNER_CI_NODE="${NODE_INDEX}"
            echo "Running ddtest node ${NODE_INDEX}"
            ./bin/ddtest run --platform ruby --framework rspec

workflows:
  test:
    jobs:
      - test
